# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='timed_score',
            field=models.IntegerField(),
        ),
    ]
