# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_auto_20180626_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='string',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
